name: Test, Build, Push, and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  test-build-push-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t iamdivye/express-k8s:latest .

    # Step 5: Tag Docker image
    - name: Tag Docker image with branch, short hash, and timestamp
      env:
        GIT_BRANCH: ${{ github.ref_name }}
        SHORT_SHA: ${{ github.sha }}
      run: |
        SHORT_SHA=${SHORT_SHA:0:7}
        SHORT_TIMESTAMP=$(date +%y%m%d%H%M)
        docker tag iamdivye/express-k8s:latest iamdivye/express-k8s:${GIT_BRANCH}-${SHORT_SHA}-${SHORT_TIMESTAMP}

    # Step 6: Login to Docker Hub
    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    # Step 7: Push Docker image
    - name: Push Docker image to Docker Hub
      env:
        GIT_BRANCH: ${{ github.ref_name }}
        SHORT_SHA: ${{ github.sha }}
      run: |
        SHORT_SHA=${SHORT_SHA:0:7}
        SHORT_TIMESTAMP=$(date +%y%m%d%H%M)
        docker push iamdivye/express-k8s:${GIT_BRANCH}-${SHORT_SHA}-${SHORT_TIMESTAMP}

    # Step 8: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Step 9: Handle Deployment and Service Recreation
    - name: Delete Deployment and Service
      run: |
        echo "Deleting existing Deployment and Service if they exist..."
        kubectl delete deployment nodeapp-deployment || echo "Deployment not found"
        kubectl delete service nodeapp-service || echo "Service not found"

    - name: Apply Kubernetes Manifests
      env:
        GIT_BRANCH: ${{ github.ref_name }}
        SHORT_SHA: ${{ github.sha }}
      run: |
        SHORT_SHA=${SHORT_SHA:0:7}
        SHORT_TIMESTAMP=$(date +%y%m%d%H%M)
        IMAGE_TAG=${GIT_BRANCH}-${SHORT_SHA}-${SHORT_TIMESTAMP}

        # Update kubeconfig
        aws eks update-kubeconfig --name my-eks-cluster --region ap-south-1

            # Step 9: Handle Deployment and Service Recreation
    - name: Delete Deployment and Service
      run: |
        echo "Deleting existing Deployment and Service if they exist..."
        kubectl delete deployment nodeapp-deployment || echo "Deployment not found"
        kubectl delete service nodeapp-service || echo "Service not found"



        # Apply manifests
        echo "Recreating Deployment and Service..."
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

        # Ensure rollout success
        echo "Waiting for rollout to complete..."
        kubectl rollout status deployment/nodeapp-deployment
